name: Acceptance Criteria

on: [push, pull_request]

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  full:
    name: Full test on Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout from Github
      uses: actions/checkout@v1
    - name: Set up the JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Compile all modules without testing
      run: mvn --batch-mode clean install dependency:go-offline -Dgpg.skip -DskipTests
    - name: Test all modules
      run: mvn --batch-mode install -Dassembly.skipAssembly -Denforcer.skip -Dgpg.skip -Dpit.skip=true
    - name: Test all modules incl. PITest and JaCoCo
      run: mvn --batch-mode org.jacoco:jacoco-maven-plugin:prepare-agent verify org.jacoco:jacoco-maven-plugin:report -Dassembly.skipAssembly -Denforcer.skip -Dgpg.skip
    - name: Trigger SonarCloud
      run: mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=robozonky -Dsonar.projectKey=com.github.robozonky:robozonky
  quick:
    name: Cross-platform sanity check
    strategy:
      fail-fast: false # Always see all results on all platforms.
      matrix:
      - name: 13@Linux
        os: ubuntu-latest
        jvm: 13
      - name: 11@Windows
        os: windows-latest
        jvm: 11
      - name: 13@Windows
        os: windows-latest
        jvm: 13
      - name: 11@MacOS
        os: macos-latest
        jvm: 11
      - name: 13@MacOS
        os: macos-latest
        jvm: 13
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout from Github
      uses: actions/checkout@v1
    - name: Set up the JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jvm }}
    - name: Compile and test all modules, skipping mutation coverage
      shell: bash
      run: mvn --batch-mode verify -Denforcer.skip -Dgpg.skip -Dpit.skip=true
